<a href="https://colab.research.google.com/github/Priyankamunrathi/Employee-repository/blob/main/Employee_productivity.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
#A company wants to predict employee productivity scores to improve workforce planning and training programs.
#You are hired as a Data Scientist to build a multivariate linear regression model that predicts
#an employee’s Productivity Score based on multiple work-related factors.

import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split, learning_curve
from sklearn.linear_model import LinearRegression
import io
from sklearn.metrics import accuracy_score, r2_score


In [7]:
csv_data = """Experience (yrs),Training Hours,Working Hours,Projects,Productivity Score
2,40,38,3,62
5,60,42,6,78
1,20,35,2,55
8,80,45,8,88
4,50,40,5,72
10,90,48,9,92
3,30,37,4,65
6,70,44,7,82
7,75,46,7,85
2,25,36,3,60"""


In [8]:
df = pd.read_csv(io.StringIO(csv_data),sep = ',')

df.describe()



,Experience (yrs),Training Hours,Working Hours,Projects,Productivity Score
count,10.000000,10.000000,10.000000,10.000000,10.000000
mean,4.800000,54.000000,41.100000,5.400000,73.900000
std,2.936362,24.698178,4.557046,2.366432,12.939603
min,1.000000,20.000000,35.000000,2.000000,55.000000
25%,2.250000,32.500000,37.250000,3.250000,62.750000
50%,4.500000,55.000000,41.000000,5.500000,75.000000
75%,6.750000,73.750000,44.750000,7.000000,84.250000
max,10.000000,90.000000,48.000000,9.000000,92.000000


In [9]:
correlations = df.corr(method='pearson')['Productivity Score'].abs().sort_values(ascending=False)
print(correlations)

Productivity Score    1.000000
Projects              0.995696
Training Hours        0.987045
Working Hours         0.985684
Experience (yrs)      0.981991
Name: Productivity Score, dtype: float64


In [10]:
#Based on correlation index, projects column mostly impact productivity with 99.6% correlation

X = df.drop('Productivity Score', axis=1)
y = df['Productivity Score']


In [16]:
# As the % of train data increases, productivity numbers match closer to actual productity (test data for same feaatures)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2,random_state=42)
model = LinearRegression()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)


In [12]:
y_train_pred = model.predict(X_train)
y_test_pred = model.predict(X_test)



In [13]:
train_r2 = r2_score(y_train, y_train_pred)
test_r2 = r2_score(y_test, y_test_pred)


In [14]:
print(f"Training R-squared: {train_r2:.3f}")
print(f"Test R-squared: {test_r2:.3f}")


Training R-squared: 1.000
Test R-squared: 0.315


In [19]:
if train_r2 > test_r2 + 0.1:
    print("The model may be overfitting.")
else:
    print("The model's performance is consistent across training and test sets.")

train_sizes, train_scores, test_scores = learning_curve(model, X, y, cv=5, n_jobs=-1, train_sizes=np.linspace(0.1, 1.0, 5))

print("Train scores: ", train_scores, "\nTest Scores: ", test_scores)



The model may be overfitting.
Train scores:  [[       nan        nan        nan        nan        nan]
 [1.         1.         1.         1.         1.        ]
 [1.         1.         1.         1.         1.        ]
 [0.99989612 0.99893305 0.99939711 0.9999482  0.9999482 ]
 [0.99726843 0.99761746 0.99867488 0.99925783 0.99922849]] 
Test Scores:  [[-3.515625   -0.33149679 -4.         -1.83044983 -0.7056    ]
 [ 0.87696961  0.80954959  0.49314957  0.16119068  0.64054715]
 [ 0.76805717  0.99829929  0.84884185  0.95516032  0.94279724]
 [ 0.99071048  0.9936231   0.831875    0.98227686  0.981271  ]
 [ 0.99269826  0.99034177  0.95320759  0.95627987  0.95721061]]


In [26]:
## Original prediction
original = model.predict(X_test)

# Experience increase
X_exp = X_test.copy()
X_exp['Experience (yrs)'] += 2
print("Experience increased:", model.predict(X_exp))

# Training increase
X_train_inc = X_test.copy()
X_train_inc['Training Hours'] += 10
print("Training increased:", model.predict(X_train_inc))

# Working hours increase
X_work = X_test.copy()
X_work['Working Hours'] += 10
print("Working hours increased:", model.predict(X_work))

# Projects increase
X_proj = X_test.copy()
X_proj['Projects'] += 5
print("Projects increased:", model.predict(X_proj))

Experience increased: [80.51543943 76.40855107]
Training increased: [83.7695962  79.66270784]
Working hours increased: [70.18764846 66.0807601 ]
Projects increased: [105.47268409 101.36579572]
